### PR TITLE
Allow store directory to be configured

### PR DESCRIPTION
**Pull request by sesmith177**
- groot.Run now takes a creator interfaces that can be used to create a
new driver with the given config

- added store directory to the groot config

### CODE REVIEW

**Comment by julz** [comment]
out of interest why pass in a Creator rather than just using the constructor of your Driver interface?

**Comment by sesmith177** [comment]
Before this PR, the constructor of the Driver interface would have to be called before passing the driver to `groot.Run`. This way, the groot library can handle all the command line arg handling / yaml parsing before the Driver is constructed

**Comment by julz** [comment]
why not just have each use its own config file? that would also avoid having to change groot every time a driver needs its own config..

**Comment by sesmith177** [comment]
We don't that would work well, as passing that config on the command line (e.g. with `--driver-config conf.yml`) would cause the CLI parsing done in the groot library to fail.  So our main.go would have to strip those arguments before calling into the groot library.

**Comment by sesmith177** [comment]
Stepping back a bit, what we would really like here is a way for the groot library to read the store directory from the command line / config file and pass it to the driver.  Any other solution which accomplishes that (e.g. adding a `SetStoreDir` method to the interface, passing the store dir to every `Unpack`/`Bundle`/`Delete`/`Exists` call, keeping the `Creator` pattern but only giving it a store directory) would probably be ok on our end.

It feels like pretty much any driver would need a way to be configured with a directory to write the container image bits in

**Comment by julz** [comment]
Gotcha. Sounds like what we really want is to be able to add some extra flags to the parsing. What do you think about adding an array of cli.Flags to the param list of Run and having Run add them to the list of flags it puts on the cli.App? That’d let you do:

~~~~
groot.Run(myDriver, os.Args, cli.StringFlag{ Name: “driver-store-path”, Destination: &myDriver.StorePath })
~~~~

This way you can get all the extra flags you want (e.g. the overlay driver on Linux will need a UID mapping range flag) without needing a shared config struct between the two. Alternatively we could make it so instead of Run we have NewApp and the client does NewApp(driver).Run(os.Args).. that’d let the client add any extra Args and such before running.

**Comment by sesmith177** [comment]
Sounds good to us -- we've just pushed a commit implementing that

**Pull request merged**
